---
- hosts: k3s_cluster
  tasks:
  - name: install apt pre-requisites
    become: yes
    apt:
      name:
        - python3-pip
      update_cache: yes
  - name: install pip pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
  - name: copy kubeconfig to home directory
    become: yes
    ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /home/{{ ansible_user }}/.kube/config 
      remote_src: true
      owner: '{{ ansible_user }}'
      mode: '0644'
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      host: https://192.168.178.108:6443/
      kind: Pod
    register: pod_list
  - name: Create monitoring namespace
    kubernetes.core.k8s:
      name: monitoring
      api_version: v1
      kind: Namespace
      state: present
  - name: Create influxdb persistent volume 
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/influxdb-persistent-volume.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create influxdb persistent volume claim
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/influxdb-persistent-volume-claim.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create influxdb Deployment
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/influxdb-deployment.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create grafana Deployment
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/grafana-deployment.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create grafana service
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/grafana-service.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create telegraf config configmap
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/telegraf-config-configmap.yaml') | from_yaml }}"
      namespace: monitoring'
  - name: Create telegraf Deployment
    kubernetes.core.k8s:
      api_version: v1
      state: present
      definition: "{{ lookup('file', 'custom-resources/telegraf-deployment.yaml') | from_yaml }}"
      namespace: monitoring'
