apiVersion: v1
kind: Service
metadata:
  name: weather-forecast
  namespace: machinelearning
spec:
  type: ClusterIP
  selector:
    app: weather-forecast
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
