---
apiVersion: v1  
kind: Secret  
metadata:  
  name: influxdb-secrets
  namespace: monitoring
type: Opaque  
stringData:  
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: password
  DOCKER_INFLUXDB_INIT_ORG: monitoring
  DOCKER_INFLUXDB_INIT_BUCKET: monitoring
  DOCKER_INFLUXDB_INIT_RETENTION: 1w
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: thesupersecrettoken
