version: '3'
services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - target

  target:
    image: alpine
    command: ["sh", "-c", "echo 'HTTP/1.1 200 OK\n\nHello, world!' | nc -l -p 8080"]
