---
- hosts: k3s_cluster
  vars:
    local_source_dir: ../dag/  # Change to your local directory containing files
    pv_target_dir: /data/pv001  # Path on the host where PV will be mounted
    namespace: airflow  # The namespace where the PVC should be created
  tasks:
  # retries are required to ensure everything is ready after k3s installation.
  - name: install apt pre-requisites
    become: yes
    apt:
      name:
        - python3-pip
        - snap
      update_cache: yes
    retries: 10
    delay: 30
  - name: install pip pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
  - name: install helm
    become: yes
    snap:
      name:
        - helm
      classic: true
  - name: install Helm Diff Plugin
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff
      state: present
  - name: copy kubeconfig to home directory
    become: yes
    ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /home/{{ ansible_user }}/.kube/config 
      remote_src: true
      owner: '{{ ansible_user }}'
      mode: '0700'
  - name: Create monitoring namespace
    kubernetes.core.k8s:
      name: monitoring
      api_version: v1
      kind: Namespace
      state: present
  - name: Add stable grafana chart repo
    kubernetes.core.helm_repository:
      name: grafana
      repo_url: "https://grafana.github.io/helm-charts"
  - name: Add stable influxdata chart repo
    kubernetes.core.helm_repository:
      name: influxdata
      repo_url: "https://helm.influxdata.com/"
  - name: Add airflow chart repo
    kubernetes.core.helm_repository:
      name: apache-airflow
      repo_url: "https://airflow.apache.org/"
  - name: Add apache bitnami chart repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "https://charts.bitnami.com/bitnami"
  - name: Update Helm Repos
    command: helm repo update
  - name: Deploy latest version of Grafana chart inside monitoring namespace with values
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: monitoring
      values:
        replicas: 1
        ingress:
          enabled: true
          hosts:
            - tig.grafana.local
          path: /
  - name: Deploy and configure latest version of Influxdb2 chart
    kubernetes.core.helm:
      name: influxdb
      chart_ref: influxdata/influxdb2
      release_namespace: monitoring
      values:
        ingress:
          enabled: true
          hostname: tig.influxdb.local
          className: traefik
          path: /
        service:
          type: ClusterIP 
          nodePort: 30000
        adminUser:
          organization: "influxdata"
          bucket: "default"
          user: "admin"
          password: "password"
          token: "securetoken"
  - name: Deploy and configure latest version of Telegraf chart
    kubernetes.core.helm:
      name: telegraf
      chart_ref: influxdata/telegraf
      release_namespace: monitoring
      values:
        service:
          enabled: false
        config:
          inputs:
            - http:
                urls:
                  - "https://dwd.api.proxy.bund.dev/v30/stationOverviewExtended?stationIds=10838,10840"
                method: "GET"
                interval: "10s"
                response_timeout: "10s"
                data_format: "json"
          outputs:
            - influxdb_v2:
                urls:
                  - "http://influxdb-influxdb2.monitoring.svc.cluster.local:80"
                organization: "influxdata"
                bucket: "default"
                token: "securetoken"
  # Due to ressource limitations on the test environment persistence is partly disabled.
  - name: Install mlflow from bitnahmi helm chart
    kubernetes.core.helm:
      name: mlflow
      chart_ref: bitnami/mlflow
      release_namespace: machinelearning
      create_namespace: true
      values:
        minio:
          enabled: false
        postgresql:
          enabled: true
          auth:
            username: kjaEftBIal
            password: s5GHwTzKip
        tracking:
          service:
            ports:
              http: 30001 
          auth:
            username: user
            password: password
          ingress:
            enabled: true
  - name: Install docker related packages
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  - name: Add GPG-Key hinzu
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
  - name: Update Packages List
    become: yes
    apt:
      update_cache: yes
    register: update_result
    retries: 3
    delay: 10
    until: update_result is succeeded
  - name: Install Docker
    become: yes
    apt:
      name: docker-ce
      state: present
  - name: Ensure Docker service is running
    become: yes
    systemd:
      name: docker
      enabled: yes
      state: started
  - name: Ensure the Docker registry container is running
    become: yes
    community.docker.docker_container:
      name: registry
      image: registry:2
      state: started
      restart_policy: always
      published_ports:
        - "5000:5000"
  - name: Configure Docker to use insecure registry
    become: yes
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      mode: '0644'
  - name: Restart Docker to apply changes
    become: yes
    systemd:
      name: docker
      state: restarted
      enabled: yes
  - name: Ensure the directory exists on the host for PV
    become: yes
    ansible.builtin.file:
      path: "{{ pv_target_dir }}"
      state: directory
      mode: '0755'
  - name: Copy all dags from the repo directory to the airflow PV directory
    become: yes
    ansible.builtin.synchronize:
      src: "{{ local_source_dir }}/"
      dest: "{{ pv_target_dir }}"
      mode: push
      recursive: yes
  - name: Create PersistentVolume
    k8s:
      definition:
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: airflow-pv
        spec:
          capacity:
            storage: 1Gi
          accessModes:
            - ReadWriteMany
          persistentVolumeReclaimPolicy: Retain
          storageClassName: manual
          hostPath:
            path: "{{ pv_target_dir }}"
  - name: Create monitoring namespace
    kubernetes.core.k8s:
      name: airflow
      api_version: v1
      kind: Namespace
      state: present
  - name: Create PersistentVolumeClaim in the airflow namespace
    k8s:
      definition:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: airflow-pvc
          namespace: "{{ namespace }}"  # PVC in airflow namespace
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
          storageClassName: manual
  - name: Deploy latest version of Apache Airlfow chart inside its own namespace with values
    kubernetes.core.helm:
      name: airflow
      chart_ref: apache-airflow/airflow
      release_namespace: airflow
      values:
        config:
          webserver:
            expose_config: True
        dags:
          persistence:
            enabled: true
            existingClaim: airflow-pvc
          gitSync:
            enabled: false
        ingress:
          web:
            enabled: true
            path: "/"
            hosts:
              - apache-airflow.local
        defaultAirflowRepository: localhost:5000/custom-airflow
        defaultAirflowTag: "1.01"