# .github/workflows/codecheck.yml
name: Code Check
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbqa black ansible pydocstyle ansible-lint
    - name: Lint Jupyter Notebooks
      run: |
        nbqa black . --check
    - name: Lint Python Files with black
      run: |
        black . --check
    - name: Check Python Documentation with pydocstyle
      run: |
        pydocstyle .
    - name: Lint Ansible Playbooks
      run: |
        ansible-lint --offline setup/cluster_setup.yml setup/ml_monitoring_setup.yml 
