# .github/workflows/codecheck.yml
name: Testing
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert requests IPython
    - name: Test DWD Api Notebook
      run: |
        jupyter nbconvert --to script ./notebooks/dwd_api.ipynb  --output-dir=./notebooks
        sed -Ei 's/\bdisplay\b/print/g' ./notebooks/dwd_api.py
        python3 ./tests/test_dwd_api.py
    - name: Test Database Connection Notebook
      run: |
        jupyter nbconvert --to script ./notebooks/database_connection.ipynb  --output-dir=./notebooks
        sed -Ei 's/\bdisplay\b/print/g' ./notebooks/database_connection.py
        python3 ./tests/test_database_connection.py
    - name: Test Docker Container Notebook 
      run: |
        jupyter nbconvert --to script ./notebooks/docker_container.ipynb  --output-dir=./notebooks
        sed -Ei 's/\bdisplay\b/print/g' ./notebooks/docker_container.py
        python3 ./tests/test_docker_container.py
    - name: Test Feature Selection Notebook 
      run: |
        jupyter nbconvert --to script ./notebooks/feature_selection.ipynb  --output-dir=./notebooks
        sed -Ei 's/\bdisplay\b/print/g' ./notebooks/feature_selection.py
        python3 ./tests/test_feature_selection.py
    - name: Test Isolation Forest Notebook 
      run: |
        jupyter nbconvert --to script ./notebooks/isolation_forest_with_pca.ipynb  --output-dir=./notebooks
        sed -Ei 's/\bdisplay\b/print/g' ./notebooks/isolation_forest_with_pca.py
        python3 ./tests/test_isolation_forest_with_pca.py
